server:
  port: 8080

project:
  version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://${HOST_NAME:localhost}:${HOST_PORT:3306}/${MYSQL_DATABASE:smartosc}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:smartosc2024}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

springdoc:
  swagger-ui:
    path=/swagger-ui:
      html:

jwt:
  secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  tokenExpirationMs: 86400000
  refreshExpirationMs: 604800000